using System.Net;
using CommonTestUtilities.Requests;
using Microsoft.Extensions.DependencyInjection;
using server.Communication.Requests;
using server.Communication.Responses;
using server.Domain.Entities;
using server.Domain.Entities.Enums;
using server.Domain.Interfaces;
using server.Domain.Models;
using Shouldly;
using WebApi.Test.Infrastructure;
using Xunit;

namespace WebApi.Test.Transactions;

[Collection(ServerApiCollection.Name)]
public class TransactionControllerInstallmentPreviewHappyPathTest(ServerWebApplicationFactory factory)
{
    private readonly HttpClient _client = factory.CreateClient();

    [Fact]
    public async Task PreviewInstallment_ShouldReturn200AndNotPersistRows_WhenManagerSendsManualInstallments()
    {
        var (user, branch, _, token) = await factory.SeedFullBranchContextAsync("TxnPreviewManualMgr", Role.Manager);
        await factory.SeedOperatorAsync(branch.Id, userId: user.Id);
        var account = await factory.SeedAccountAsync(branch.Id, AccountType.Terminal);
        var category = await factory.SeedCategoryAsync(branch.Id, "Saídas", Direction.Out);
        var transactionType = await factory.SeedTransactionTypeAsync(
            category.Id,
            settlementRule: SettlementRule.OperatorEnteredCheque);

        var countBefore = await CountTransactionsAsync(branch.Id);

        var firstDueDate = DateTime.Today.AddDays(30);
        var request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithDate(DateTime.Today)
            .WithDescription("Cheque preview")
            .WithValue(300.00m)
            .WithTransactionTypeId(transactionType.Id)
            .WithAccountId(account.Id)
            .WithInstallments(
            [
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate, Value = 100.00m },
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate.AddDays(30), Value = 100.00m },
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate.AddDays(60), Value = 100.00m }
            ])
            .Build();

        var httpResponse = await _client.PostAuthAsync("/transaction/installment/preview", request, token);

        httpResponse.StatusCode.ShouldBe(HttpStatusCode.OK);
        var payload = await httpResponse.ReadContentAsync<ResponseInstallmentPreviewJson>();

        payload.TotalValue.ShouldBe(300.00m);
        payload.InstallmentCount.ShouldBe(3);
        payload.Rows.Count.ShouldBe(3);

        for (var i = 0; i < 3; i++)
        {
            payload.Rows[i].Index.ShouldBe(i + 1);
            payload.Rows[i].Value.ShouldBe(100.00m);
            payload.Rows[i].DueDate.ShouldBe(firstDueDate.AddDays(i * 30));
        }

        payload.Rows[0].Description.ShouldBe("CH PRE (1/3) - Cheque preview");
        payload.Rows[1].Description.ShouldBe("CH PRE (2/3) - Cheque preview");
        payload.Rows[2].Description.ShouldBe("CH PRE (3/3) - Cheque preview");

        var countAfter = await CountTransactionsAsync(branch.Id);
        countAfter.ShouldBe(countBefore);
    }

    [Fact]
    public async Task PreviewInstallment_ShouldReturn200AndNotPersistRows_WhenManagerSendsAutoGeneratedInstallments()
    {
        var (user, branch, _, token) = await factory.SeedFullBranchContextAsync("TxnPreviewAutoMgr", Role.Manager);
        await factory.SeedOperatorAsync(branch.Id, userId: user.Id);
        var account = await factory.SeedAccountAsync(branch.Id, AccountType.Terminal);
        var category = await factory.SeedCategoryAsync(branch.Id, "Saídas", Direction.Out);
        var transactionType = await factory.SeedTransactionTypeAsync(
            category.Id,
            settlementRule: SettlementRule.OperatorEnteredCheque);

        var countBefore = await CountTransactionsAsync(branch.Id);

        var baseDueDate = DateTime.Today.AddDays(30);
        var request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithDate(DateTime.Today)
            .WithValue(400.00m)
            .WithTransactionTypeId(transactionType.Id)
            .WithAccountId(account.Id)
            .WithAutoGeneration(4, baseDueDate)
            .Build();

        var httpResponse = await _client.PostAuthAsync("/transaction/installment/preview", request, token);

        httpResponse.StatusCode.ShouldBe(HttpStatusCode.OK);
        var payload = await httpResponse.ReadContentAsync<ResponseInstallmentPreviewJson>();

        payload.TotalValue.ShouldBe(400.00m);
        payload.InstallmentCount.ShouldBe(4);
        payload.Rows.Count.ShouldBe(4);
        payload.Rows.Sum(r => r.Value).ShouldBe(400.00m);

        for (var i = 0; i < 4; i++)
        {
            payload.Rows[i].Index.ShouldBe(i + 1);
        }

        var countAfter = await CountTransactionsAsync(branch.Id);
        countAfter.ShouldBe(countBefore);
    }

    [Fact]
    public async Task PreviewInstallment_ShouldReturn200AndMatchWrite_WhenSamePayloadIsUsedForBoth()
    {
        // End-to-end determinism test: preview rows must match persisted rows position-for-position.
        var (user, branch, _, token) = await factory.SeedFullBranchContextAsync("TxnPreviewParity", Role.Manager);
        await factory.SeedOperatorAsync(branch.Id, userId: user.Id);
        var account = await factory.SeedAccountAsync(branch.Id, AccountType.Terminal);
        var category = await factory.SeedCategoryAsync(branch.Id, "Saídas", Direction.Out);
        var transactionType = await factory.SeedTransactionTypeAsync(
            category.Id,
            settlementRule: SettlementRule.OperatorEnteredCheque);

        var firstDueDate = DateTime.Today.AddDays(31);
        var request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithDate(DateTime.Today)
            .WithDescription("Parity test")
            .WithValue(100.01m)
            .WithTransactionTypeId(transactionType.Id)
            .WithAccountId(account.Id)
            .WithInstallments(
            [
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate, Value = 33.33m },
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate.AddDays(15), Value = 33.33m },
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate.AddDays(45), Value = 33.35m }
            ])
            .Build();

        // 1. Call preview
        var previewResponse = await _client.PostAuthAsync("/transaction/installment/preview", request, token);
        previewResponse.StatusCode.ShouldBe(HttpStatusCode.OK);
        var preview = await previewResponse.ReadContentAsync<ResponseInstallmentPreviewJson>();

        // 2. Call installment create with the same payload
        var createResponse = await _client.PostAuthAsync("/transaction/installment", request, token);
        createResponse.StatusCode.ShouldBe(HttpStatusCode.Created);
        var created = await createResponse.ReadContentAsync<ResponseCreateTransactionInstallmentJson>();

        // 3. Load persisted rows by OriginTransactionId
        var originId = created.Installments[0].Id;
        var persistedRows = await ListInstallmentsAsync(originId, branch.Id);

        persistedRows.Count.ShouldBe(preview.Rows.Count);

        for (var i = 0; i < persistedRows.Count; i++)
        {
            persistedRows[i].DueDate.ShouldBe(preview.Rows[i].DueDate);
            persistedRows[i].Value.ShouldBe(preview.Rows[i].Value);
            persistedRows[i].Description.ShouldBe(preview.Rows[i].Description);
        }
    }

    private async Task<int> CountTransactionsAsync(Guid branchId)
    {
        using var scope = factory.Services.CreateScope();
        var transactionsRepository = scope.ServiceProvider.GetRequiredService<ITransactionsRepository>();
        return await transactionsRepository.CountByBranchIdAsNoTracking(branchId, new TransactionListFilter());
    }

    private async Task<IReadOnlyList<Transaction>> ListInstallmentsAsync(Guid originId, Guid branchId)
    {
        using var scope = factory.Services.CreateScope();
        var transactionsRepository = scope.ServiceProvider.GetRequiredService<ITransactionsRepository>();
        var rows = await transactionsRepository.ListByOriginTransactionIdAndBranchIdAsNoTracking(originId, branchId);
        return rows.OrderBy(t => t.DueDate).ToList();
    }
}
