//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("server.Exceptions.ResourcesErrorMessages", typeof(ResourcesErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        public static string BRANCH_CNPJ_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_CNPJ_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string BRANCH_ID_EMPTY {
            get {
                return ResourceManager.GetString("BRANCH_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("BRANCH_USER_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_ALREADY_ACTIVE {
            get {
                return ResourceManager.GetString("BRANCH_USER_ALREADY_ACTIVE", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_LAST_ADMIN_CONFLICT {
            get {
                return ResourceManager.GetString("BRANCH_USER_LAST_ADMIN_CONFLICT", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_IDENTIFIER_EXCLUSIVE {
            get {
                return ResourceManager.GetString("BRANCH_USER_IDENTIFIER_EXCLUSIVE", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_IDENTIFIER_REQUIRED {
            get {
                return ResourceManager.GetString("BRANCH_USER_IDENTIFIER_REQUIRED", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("BRANCH_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string BRANCH_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string BRANCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("BRANCH_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string BRANCH_PHONE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_PHONE_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        public static string ROLE_INVALID {
            get {
                return ResourceManager.GetString("ROLE_INVALID", resourceCulture);
            }
        }
        
        public static string ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("ROLE_REQUIRED", resourceCulture);
            }
        }

        public static string ENUM_NAME_INVALID {
            get {
                return ResourceManager.GetString("ENUM_NAME_INVALID", resourceCulture);
            }
        }

        public static string REQUEST_INVALID {
            get {
                return ResourceManager.GetString("REQUEST_INVALID", resourceCulture);
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("USER_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string EMAIL_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_NOT_REGISTERED", resourceCulture);
            }
        }
        
        public static string PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("PASSWORD_WRONG", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_INVALID {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_INVALID", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_WITHOUT_USER {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_WITHOUT_USER", resourceCulture);
            }
        }
        
        public static string TOKEN_EMPTY {
            get {
                return ResourceManager.GetString("TOKEN_EMPTY", resourceCulture);
            }
        }
        
        public static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string TOKEN_WITHOUT_USER {
            get {
                return ResourceManager.GetString("TOKEN_WITHOUT_USER", resourceCulture);
            }
        }
        
        public static string TOKEN_WITHOUT_PERMISSION {
            get {
                return ResourceManager.GetString("TOKEN_WITHOUT_PERMISSION", resourceCulture);
            }
        }
        
        public static string OPERATOR_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("OPERATOR_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string OPERATOR_USER_NOT_BRANCH_MEMBER {
            get {
                return ResourceManager.GetString("OPERATOR_USER_NOT_BRANCH_MEMBER", resourceCulture);
            }
        }
        
        public static string OPERATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("OPERATOR_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string OPERATOR_ID_EMPTY {
            get {
                return ResourceManager.GetString("OPERATOR_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string OPERATOR_USER_ALREADY_LINKED {
            get {
                return ResourceManager.GetString("OPERATOR_USER_ALREADY_LINKED", resourceCulture);
            }
        }
        
        public static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ACCOUNT_ID_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string ACCOUNT_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string ACCOUNT_INSTITUTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ACCOUNT_INSTITUTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string ACCOUNT_NUMBER_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ACCOUNT_NUMBER_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_INVALID", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TYPE_IMMUTABLE {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_IMMUTABLE", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_CREATE_CANNOT_USE_EXISTING_AND_NEW_TAB {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_CREATE_CANNOT_USE_EXISTING_AND_NEW_TAB", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_ALREADY_LINKED {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_ALREADY_LINKED", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_ID_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TAB_ID_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_TAB_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TAB_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_TAB_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TAB_ALREADY_LINKED {
            get {
                return ResourceManager.GetString("ACCOUNT_TAB_ALREADY_LINKED", resourceCulture);
            }
        }
        
        public static string OPERATOR_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("OPERATOR_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string OPERATOR_ACCOUNT_ALREADY_ACTIVE {
            get {
                return ResourceManager.GetString("OPERATOR_ACCOUNT_ALREADY_ACTIVE", resourceCulture);
            }
        }
        
        public static string CLIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string CLIENT_ID_EMPTY {
            get {
                return ResourceManager.GetString("CLIENT_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string CLIENT_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CLIENT_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string CLIENT_PHONE_EMPTY {
            get {
                return ResourceManager.GetString("CLIENT_PHONE_EMPTY", resourceCulture);
            }
        }
        
        public static string CLIENT_PHONE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CLIENT_PHONE_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string CLIENT_CPF_INVALID {
            get {
                return ResourceManager.GetString("CLIENT_CPF_INVALID", resourceCulture);
            }
        }
        
        public static string CLIENT_CPF_CONFLICT {
            get {
                return ResourceManager.GetString("CLIENT_CPF_CONFLICT", resourceCulture);
            }
        }
        
        public static string TRANSACTION_TYPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string TRANSACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string TRANSACTION_REQUIRES_TAB_ACCOUNT_AND_CLIENT {
            get {
                return ResourceManager.GetString("TRANSACTION_REQUIRES_TAB_ACCOUNT_AND_CLIENT", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DATE_LOCKED {
            get {
                return ResourceManager.GetString("TRANSACTION_DATE_LOCKED", resourceCulture);
            }
        }

        public static string TRANSACTION_DAILY_CLOSE_LEDGER_FROZEN {
            get {
                return ResourceManager.GetString("TRANSACTION_DAILY_CLOSE_LEDGER_FROZEN", resourceCulture);
            }
        }

        public static string TRANSACTION_REQUIRES_OPEN_DAILY_CLOSE {
            get {
                return ResourceManager.GetString("TRANSACTION_REQUIRES_OPEN_DAILY_CLOSE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_ACCOUNT_OUT_OF_SCOPE {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_ACCOUNT_OUT_OF_SCOPE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_VALUE_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("TRANSACTION_VALUE_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_VALUE_PRECISION_14X2 {
            get {
                return ResourceManager.GetString("TRANSACTION_VALUE_PRECISION_14X2", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TRANSACTION_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DUE_DATE_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_DUE_DATE_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DUE_DATE_BEFORE_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_DUE_DATE_BEFORE_DATE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_PAID_AT_BEFORE_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_PAID_AT_BEFORE_DATE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_CANNOT_UPDATE_CANCELLED {
            get {
                return ResourceManager.GetString("TRANSACTION_CANNOT_UPDATE_CANCELLED", resourceCulture);
            }
        }
        
        public static string TRANSACTION_CANNOT_FINALIZE_NON_DRAFT {
            get {
                return ResourceManager.GetString("TRANSACTION_CANNOT_FINALIZE_NON_DRAFT", resourceCulture);
            }
        }

        public static string TRANSACTION_ALREADY_CANCELLED {
            get {
                return ResourceManager.GetString("TRANSACTION_ALREADY_CANCELLED", resourceCulture);
            }
        }

        public static string TRANSACTION_CANCELLATION_REASON_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_CANCELLATION_REASON_EMPTY", resourceCulture);
            }
        }

        public static string TRANSACTION_CANCELLATION_REASON_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TRANSACTION_CANCELLATION_REASON_MAX_LENGTH", resourceCulture);
            }
        }

        public static string TRANSACTION_FIADO_REQUIRES_CLIENT {
            get {
                return ResourceManager.GetString("TRANSACTION_FIADO_REQUIRES_CLIENT", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_NOT_RECORDING_OPERATOR {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_NOT_RECORDING_OPERATOR", resourceCulture);
            }
        }
        
        public static string TRANSACTION_UPDATE_REQUIRES_SAME_DAY {
            get {
                return ResourceManager.GetString("TRANSACTION_UPDATE_REQUIRES_SAME_DAY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_CANNOT_OVERRIDE_RECORDED_BY_OPERATOR {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_CANNOT_OVERRIDE_RECORDED_BY_OPERATOR", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_REQUIRES_OPERATOR_LINK {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_REQUIRES_OPERATOR_LINK", resourceCulture);
            }
        }
        
        public static string TRANSACTION_REQUIRES_RECORDED_BY_OPERATOR {
            get {
                return ResourceManager.GetString("TRANSACTION_REQUIRES_RECORDED_BY_OPERATOR", resourceCulture);
            }
        }
        
        public static string TRANSACTION_CHEQUE_REQUIRES_DUE_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_CHEQUE_REQUIRES_DUE_DATE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_COUNT_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_COUNT_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_REQUIRES_CHEQUE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_REQUIRES_CHEQUE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_AUTO_GENERATE_CANNOT_HAVE_ITEMS {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_AUTO_GENERATE_CANNOT_HAVE_ITEMS", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_TOTAL_MISMATCH {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_TOTAL_MISMATCH", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_DUE_DATES_MUST_INCREASE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_DUE_DATES_MUST_INCREASE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_FIRST_DUE_DATE_MUST_BE_FUTURE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_FIRST_DUE_DATE_MUST_BE_FUTURE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_ROW_VALUE_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_ROW_VALUE_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DATE_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_DATE_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_TYPE_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_ACCOUNT_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_ACCOUNT_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_RECORDED_BY_OPERATOR_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_RECORDED_BY_OPERATOR_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_STATUS_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_STATUS_INVALID", resourceCulture);
            }
        }

        public static string TRANSACTION_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_PAGE_INVALID", resourceCulture);
            }
        }
        
        public static string TRANSACTION_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }
        
        public static string TRANSACTION_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }

        public static string TRANSACTION_LIST_MINE_AND_OPERATOR_ID_CONFLICT {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_MINE_AND_OPERATOR_ID_CONFLICT", resourceCulture);
            }
        }

        public static string DAILYCLOSE_STATUS_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_STATUS_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_FOUND {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_FOUND", resourceCulture);
            }
        }

        public static string DAILYCLOSE_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_DATE_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ACCOUNT_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ACCOUNT_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ACCOUNT_NOT_TERMINAL {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ACCOUNT_NOT_TERMINAL", resourceCulture);
            }
        }

        public static string DAILYCLOSE_FUTURE_DATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_FUTURE_DATE_NOT_ALLOWED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_MEMBER_OPEN_REQUIRES_TODAY {
            get {
                return ResourceManager.GetString("DAILYCLOSE_MEMBER_OPEN_REQUIRES_TODAY", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LOCK_DATE_VIOLATION {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LOCK_DATE_VIOLATION", resourceCulture);
            }
        }

        public static string DAILYCLOSE_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("DAILYCLOSE_DATE_CONFLICT", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_DUPLICATE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_DUPLICATE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_EDITABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_SUBMITTABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_SUBMITTABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_APPROVABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_APPROVABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_REJECTABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_REJECTABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_RECALLABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_RECALLABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_REOPENABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_REOPENABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_RECALL_REQUIRES_SAME_DAY {
            get {
                return ResourceManager.GetString("DAILYCLOSE_RECALL_REQUIRES_SAME_DAY", resourceCulture);
            }
        }

        public static string DAILYCLOSE_OUTSTANDING_DRAFT_TRANSACTIONS {
            get {
                return ResourceManager.GetString("DAILYCLOSE_OUTSTANDING_DRAFT_TRANSACTIONS", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEMS_NOT_RECORDED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEMS_NOT_RECORDED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_PRIOR_DAY_NOT_COUNTED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_PRIOR_DAY_NOT_COUNTED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LEDGER_COORDINATION_BUSY {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LEDGER_COORDINATION_BUSY", resourceCulture);
            }
        }

        public static string DAILYCLOSE_REJECTION_REASON_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_REJECTION_REASON_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_REJECTION_REASON_LENGTH {
            get {
                return ResourceManager.GetString("DAILYCLOSE_REJECTION_REASON_LENGTH", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_PRODUCT_FORBIDDEN {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_PRODUCT_FORBIDDEN", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_VALUE_NEGATIVE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_VALUE_NEGATIVE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_VALUE_PRECISION {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_VALUE_PRECISION", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEMS_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEMS_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_PRODUCT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_PRODUCT_ID_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_PRODUCT_NOT_FOUND", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOTES_LENGTH {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOTES_LENGTH", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOTES_FROZEN {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOTES_FROZEN", resourceCulture);
            }
        }

        public static string DAILYCLOSE_STALE_WRITE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_STALE_WRITE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_BRANCH_MISMATCH {
            get {
                return ResourceManager.GetString("DAILYCLOSE_BRANCH_MISMATCH", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_PAGE_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_MINE_AND_OPERATOR_ID_CONFLICT {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_MINE_AND_OPERATOR_ID_CONFLICT", resourceCulture);
            }
        }

        public static string TIMEENTRY_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("TIMEENTRY_DATE_CONFLICT", resourceCulture);
            }
        }

        public static string TIMEENTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("TIMEENTRY_NOT_FOUND", resourceCulture);
            }
        }

        public static string TIMEENTRY_ID_EMPTY {
            get {
                return ResourceManager.GetString("TIMEENTRY_ID_EMPTY", resourceCulture);
            }
        }

        public static string TIMEENTRY_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("TIMEENTRY_DATE_REQUIRED", resourceCulture);
            }
        }

        public static string TIMEENTRY_DATE_LOCKED {
            get {
                return ResourceManager.GetString("TIMEENTRY_DATE_LOCKED", resourceCulture);
            }
        }

        public static string TIMEENTRY_STATUS_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_STATUS_INVALID", resourceCulture);
            }
        }

        public static string TIMEENTRY_OPERATOR_ID_REQUIRED {
            get {
                return ResourceManager.GetString("TIMEENTRY_OPERATOR_ID_REQUIRED", resourceCulture);
            }
        }

        public static string TIMEENTRY_NOT_OWN_OPERATOR {
            get {
                return ResourceManager.GetString("TIMEENTRY_NOT_OWN_OPERATOR", resourceCulture);
            }
        }

        public static string TIMEENTRY_REQUIRES_OPERATOR_LINK {
            get {
                return ResourceManager.GetString("TIMEENTRY_REQUIRES_OPERATOR_LINK", resourceCulture);
            }
        }

        public static string TIMEENTRY_WRITE_REQUIRES_SAME_DAY {
            get {
                return ResourceManager.GetString("TIMEENTRY_WRITE_REQUIRES_SAME_DAY", resourceCulture);
            }
        }

        public static string TIMEENTRY_MEMBER_ONLY_PRESENT {
            get {
                return ResourceManager.GetString("TIMEENTRY_MEMBER_ONLY_PRESENT", resourceCulture);
            }
        }

        public static string TIMEENTRY_CLOCKS_EQUAL {
            get {
                return ResourceManager.GetString("TIMEENTRY_CLOCKS_EQUAL", resourceCulture);
            }
        }

        public static string TIMEENTRY_SEGMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TIMEENTRY_SEGMENT_NOT_FOUND", resourceCulture);
            }
        }

        public static string TIMEENTRY_SEGMENT_CLOCK_IN_LOCKED {
            get {
                return ResourceManager.GetString("TIMEENTRY_SEGMENT_CLOCK_IN_LOCKED", resourceCulture);
            }
        }

        public static string TIMEENTRY_SEGMENTS_OVERLAP {
            get {
                return ResourceManager.GetString("TIMEENTRY_SEGMENTS_OVERLAP", resourceCulture);
            }
        }

        public static string TIMEENTRY_MULTIPLE_OPEN_SEGMENTS {
            get {
                return ResourceManager.GetString("TIMEENTRY_MULTIPLE_OPEN_SEGMENTS", resourceCulture);
            }
        }

        public static string TIMEENTRY_NON_PRESENT_REJECTS_SEGMENTS {
            get {
                return ResourceManager.GetString("TIMEENTRY_NON_PRESENT_REJECTS_SEGMENTS", resourceCulture);
            }
        }

        public static string TIMEENTRY_STATUS_CHANGE_REQUIRES_SEGMENT_CLEANUP {
            get {
                return ResourceManager.GetString("TIMEENTRY_STATUS_CHANGE_REQUIRES_SEGMENT_CLEANUP", resourceCulture);
            }
        }

        public static string TIMEENTRY_SEGMENT_OUT_OF_DAY_BOUNDS {
            get {
                return ResourceManager.GetString("TIMEENTRY_SEGMENT_OUT_OF_DAY_BOUNDS", resourceCulture);
            }
        }

        public static string TIMEENTRY_MEMBER_TAP_ACTION_REQUIRED {
            get {
                return ResourceManager.GetString("TIMEENTRY_MEMBER_TAP_ACTION_REQUIRED", resourceCulture);
            }
        }

        public static string TIMEENTRY_MEMBER_SHOULD_NOT_SEND_SEGMENTS {
            get {
                return ResourceManager.GetString("TIMEENTRY_MEMBER_SHOULD_NOT_SEND_SEGMENTS", resourceCulture);
            }
        }

        public static string TIMEENTRY_ADMIN_REQUIRES_SEGMENTS {
            get {
                return ResourceManager.GetString("TIMEENTRY_ADMIN_REQUIRES_SEGMENTS", resourceCulture);
            }
        }

        public static string TIMEENTRY_ADMIN_SHOULD_NOT_SEND_TAP_ACTION {
            get {
                return ResourceManager.GetString("TIMEENTRY_ADMIN_SHOULD_NOT_SEND_TAP_ACTION", resourceCulture);
            }
        }

        public static string TIMEENTRY_OPEN_SEGMENT_CONFLICT {
            get {
                return ResourceManager.GetString("TIMEENTRY_OPEN_SEGMENT_CONFLICT", resourceCulture);
            }
        }

        public static string TIMEENTRY_SEGMENT_CLOCK_IN_REQUIRED {
            get {
                return ResourceManager.GetString("TIMEENTRY_SEGMENT_CLOCK_IN_REQUIRED", resourceCulture);
            }
        }

        public static string TIMEENTRY_SEGMENT_CLOCK_OUT_BEFORE_CLOCK_IN {
            get {
                return ResourceManager.GetString("TIMEENTRY_SEGMENT_CLOCK_OUT_BEFORE_CLOCK_IN", resourceCulture);
            }
        }

        public static string TIMEENTRY_SUNDAY_REQUIRES_SUNDAY_DATE {
            get {
                return ResourceManager.GetString("TIMEENTRY_SUNDAY_REQUIRES_SUNDAY_DATE", resourceCulture);
            }
        }

        public static string TIMEENTRY_HOLIDAY_REQUIRES_ACTIVE_HOLIDAY {
            get {
                return ResourceManager.GetString("TIMEENTRY_HOLIDAY_REQUIRES_ACTIVE_HOLIDAY", resourceCulture);
            }
        }

        public static string TIMEENTRY_OPERATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("TIMEENTRY_OPERATOR_NOT_FOUND", resourceCulture);
            }
        }

        public static string TIMEENTRY_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_LIST_PAGE_INVALID", resourceCulture);
            }
        }

        public static string TIMEENTRY_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string TIMEENTRY_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }

        public static string TIMEENTRY_LIST_MINE_AND_OPERATOR_ID_CONFLICT {
            get {
                return ResourceManager.GetString("TIMEENTRY_LIST_MINE_AND_OPERATOR_ID_CONFLICT", resourceCulture);
            }
        }

        public static string HOLIDAY_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("HOLIDAY_DATE_CONFLICT", resourceCulture);
            }
        }

        public static string HOLIDAY_NOT_FOUND {
            get {
                return ResourceManager.GetString("HOLIDAY_NOT_FOUND", resourceCulture);
            }
        }

        public static string HOLIDAY_ID_EMPTY {
            get {
                return ResourceManager.GetString("HOLIDAY_ID_EMPTY", resourceCulture);
            }
        }

        public static string HOLIDAY_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("HOLIDAY_DATE_REQUIRED", resourceCulture);
            }
        }

        public static string HOLIDAY_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("HOLIDAY_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }

        public static string HOLIDAY_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("HOLIDAY_LIST_PAGE_INVALID", resourceCulture);
            }
        }

        public static string HOLIDAY_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("HOLIDAY_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string HOLIDAY_CREATE_BATCH_EMPTY {
            get {
                return ResourceManager.GetString("HOLIDAY_CREATE_BATCH_EMPTY", resourceCulture);
            }
        }

        public static string HOLIDAY_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("HOLIDAY_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }

        public static string HOLIDAY_IMPORT_YEAR_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("HOLIDAY_IMPORT_YEAR_OUT_OF_RANGE", resourceCulture);
            }
        }

        public static string HOLIDAY_SOURCE_UNAVAILABLE {
            get {
                return ResourceManager.GetString("HOLIDAY_SOURCE_UNAVAILABLE", resourceCulture);
            }
        }

        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }

        public static string CATEGORY_ID_EMPTY {
            get {
                return ResourceManager.GetString("CATEGORY_ID_EMPTY", resourceCulture);
            }
        }

        public static string CATEGORY_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_REQUIRED", resourceCulture);
            }
        }

        public static string CATEGORY_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_MAX_LENGTH", resourceCulture);
            }
        }

        public static string CATEGORY_DEFAULT_DIRECTION_INVALID {
            get {
                return ResourceManager.GetString("CATEGORY_DEFAULT_DIRECTION_INVALID", resourceCulture);
            }
        }

        public static string CATEGORY_NAME_CONFLICT {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_CONFLICT", resourceCulture);
            }
        }

        public static string TRANSACTION_TYPE_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_NAME_REQUIRED", resourceCulture);
            }
        }

        public static string TRANSACTION_TYPE_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_NAME_MAX_LENGTH", resourceCulture);
            }
        }

        public static string TRANSACTION_TYPE_CATEGORY_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_CATEGORY_ID_EMPTY", resourceCulture);
            }
        }

        public static string TRANSACTION_TYPE_SETTLEMENT_RULE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_SETTLEMENT_RULE_INVALID", resourceCulture);
            }
        }

        public static string TRANSACTION_TYPE_NAME_CONFLICT {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_NAME_CONFLICT", resourceCulture);
            }
        }

        public static string PRODUCT_NAME_CONFLICT {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_CONFLICT", resourceCulture);
            }
        }

        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }

        public static string PRODUCT_ID_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_ID_EMPTY", resourceCulture);
            }
        }

        public static string PRODUCT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_REQUIRED", resourceCulture);
            }
        }

        public static string PRODUCT_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_MAX_LENGTH", resourceCulture);
            }
        }

        public static string PRODUCT_DISPLAY_ORDER_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_DISPLAY_ORDER_INVALID", resourceCulture);
            }
        }

        public static string PRODUCT_SYSTEM_PROTECTED {
            get {
                return ResourceManager.GetString("PRODUCT_SYSTEM_PROTECTED", resourceCulture);
            }
        }

        public static string SETTING_LOCK_DATE_READ_ONLY {
            get {
                return ResourceManager.GetString("SETTING_LOCK_DATE_READ_ONLY", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_YEAR_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_YEAR_OUT_OF_RANGE", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_INVALID {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_INVALID", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_CURRENT_OR_FUTURE {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_CURRENT_OR_FUTURE", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_ALREADY_LOCKED {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_ALREADY_LOCKED", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_BEFORE_BRANCH_FLOOR {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_BEFORE_BRANCH_FLOOR", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_UNAPPROVED_CLOSE {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_UNAPPROVED_CLOSE", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_DRAFT_TRANSACTIONS {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_DRAFT_TRANSACTIONS", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_MISSING_EXPECTED_CLOSE {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_MISSING_EXPECTED_CLOSE", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_NO_CLOSE_WITH_EXPECTED_ACTIVITY {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_NO_CLOSE_WITH_EXPECTED_ACTIVITY", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_INTERMEDIATE_UNRESOLVED {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_INTERMEDIATE_UNRESOLVED", resourceCulture);
            }
        }

        public static string SETTING_LOCK_MONTH_COORDINATION_BUSY {
            get {
                return ResourceManager.GetString("SETTING_LOCK_MONTH_COORDINATION_BUSY", resourceCulture);
            }
        }

        public static string SETTING_DAILY_TARGET_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("SETTING_DAILY_TARGET_OUT_OF_RANGE", resourceCulture);
            }
        }

        public static string SETTING_LUNCH_DEDUCTION_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("SETTING_LUNCH_DEDUCTION_OUT_OF_RANGE", resourceCulture);
            }
        }

        public static string IDEMPOTENCY_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("IDEMPOTENCY_KEY_REQUIRED", resourceCulture);
            }
        }

        public static string IDEMPOTENCY_KEY_INVALID {
            get {
                return ResourceManager.GetString("IDEMPOTENCY_KEY_INVALID", resourceCulture);
            }
        }

        public static string IDEMPOTENCY_KEY_PAYLOAD_CONFLICT {
            get {
                return ResourceManager.GetString("IDEMPOTENCY_KEY_PAYLOAD_CONFLICT", resourceCulture);
            }
        }

        public static string IDEMPOTENCY_COORDINATION_BUSY {
            get {
                return ResourceManager.GetString("IDEMPOTENCY_COORDINATION_BUSY", resourceCulture);
            }
        }

        public static string CONCURRENCY_IF_MATCH_REQUIRED {
            get {
                return ResourceManager.GetString("CONCURRENCY_IF_MATCH_REQUIRED", resourceCulture);
            }
        }

        public static string CONCURRENCY_IF_MATCH_INVALID {
            get {
                return ResourceManager.GetString("CONCURRENCY_IF_MATCH_INVALID", resourceCulture);
            }
        }

        public static string TRANSACTION_STALE_WRITE {
            get {
                return ResourceManager.GetString("TRANSACTION_STALE_WRITE", resourceCulture);
            }
        }

        public static string SETTING_STALE_WRITE {
            get {
                return ResourceManager.GetString("SETTING_STALE_WRITE", resourceCulture);
            }
        }

        public static string REPORT_DATE_RANGE_REQUIRED {
            get {
                return ResourceManager.GetString("REPORT_DATE_RANGE_REQUIRED", resourceCulture);
            }
        }

        public static string REPORT_DATE_RANGE_INVERTED {
            get {
                return ResourceManager.GetString("REPORT_DATE_RANGE_INVERTED", resourceCulture);
            }
        }

        public static string REPORT_DATE_RANGE_TOO_WIDE {
            get {
                return ResourceManager.GetString("REPORT_DATE_RANGE_TOO_WIDE", resourceCulture);
            }
        }

        public static string REPORT_AS_OF_DATE_INVALID {
            get {
                return ResourceManager.GetString("REPORT_AS_OF_DATE_INVALID", resourceCulture);
            }
        }

        public static string REPORT_YEAR_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("REPORT_YEAR_OUT_OF_RANGE", resourceCulture);
            }
        }

        public static string REPORT_MONTH_INVALID {
            get {
                return ResourceManager.GetString("REPORT_MONTH_INVALID", resourceCulture);
            }
        }

        public static string REPORT_OPERATOR_ID_REQUIRED {
            get {
                return ResourceManager.GetString("REPORT_OPERATOR_ID_REQUIRED", resourceCulture);
            }
        }

        public static string REPORT_ACCOUNT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("REPORT_ACCOUNT_ID_REQUIRED", resourceCulture);
            }
        }

        public static string REPORT_MEMBER_NOT_OWN_OPERATOR {
            get {
                return ResourceManager.GetString("REPORT_MEMBER_NOT_OWN_OPERATOR", resourceCulture);
            }
        }

        public static string REPORT_PAGE_INVALID {
            get {
                return ResourceManager.GetString("REPORT_PAGE_INVALID", resourceCulture);
            }
        }

        public static string REPORT_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("REPORT_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string REPORT_MINE_AND_OPERATOR_ID_CONFLICT {
            get {
                return ResourceManager.GetString("REPORT_MINE_AND_OPERATOR_ID_CONFLICT", resourceCulture);
            }
        }
    }
}
