//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("server.Exceptions.ResourcesErrorMessages", typeof(ResourcesErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        public static string BRANCH_CNPJ_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_CNPJ_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string BRANCH_ID_EMPTY {
            get {
                return ResourceManager.GetString("BRANCH_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("BRANCH_USER_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_ALREADY_ACTIVE {
            get {
                return ResourceManager.GetString("BRANCH_USER_ALREADY_ACTIVE", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_LAST_ADMIN_CONFLICT {
            get {
                return ResourceManager.GetString("BRANCH_USER_LAST_ADMIN_CONFLICT", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_IDENTIFIER_EXCLUSIVE {
            get {
                return ResourceManager.GetString("BRANCH_USER_IDENTIFIER_EXCLUSIVE", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_IDENTIFIER_REQUIRED {
            get {
                return ResourceManager.GetString("BRANCH_USER_IDENTIFIER_REQUIRED", resourceCulture);
            }
        }
        
        public static string BRANCH_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("BRANCH_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string BRANCH_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string BRANCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("BRANCH_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string BRANCH_PHONE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_PHONE_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        public static string ROLE_INVALID {
            get {
                return ResourceManager.GetString("ROLE_INVALID", resourceCulture);
            }
        }
        
        public static string ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("ROLE_REQUIRED", resourceCulture);
            }
        }
        
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        public static string USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("USER_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string EMAIL_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_NOT_REGISTERED", resourceCulture);
            }
        }
        
        public static string PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("PASSWORD_WRONG", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_INVALID {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_INVALID", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_WITHOUT_USER {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_WITHOUT_USER", resourceCulture);
            }
        }
        
        public static string TOKEN_EMPTY {
            get {
                return ResourceManager.GetString("TOKEN_EMPTY", resourceCulture);
            }
        }
        
        public static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string TOKEN_WITHOUT_USER {
            get {
                return ResourceManager.GetString("TOKEN_WITHOUT_USER", resourceCulture);
            }
        }
        
        public static string TOKEN_WITHOUT_PERMISSION {
            get {
                return ResourceManager.GetString("TOKEN_WITHOUT_PERMISSION", resourceCulture);
            }
        }
        
        public static string OPERATOR_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("OPERATOR_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string OPERATOR_USER_NOT_BRANCH_MEMBER {
            get {
                return ResourceManager.GetString("OPERATOR_USER_NOT_BRANCH_MEMBER", resourceCulture);
            }
        }
        
        public static string OPERATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("OPERATOR_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string OPERATOR_ID_EMPTY {
            get {
                return ResourceManager.GetString("OPERATOR_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string OPERATOR_USER_ALREADY_LINKED {
            get {
                return ResourceManager.GetString("OPERATOR_USER_ALREADY_LINKED", resourceCulture);
            }
        }
        
        public static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ACCOUNT_ID_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string ACCOUNT_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string ACCOUNT_INSTITUTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ACCOUNT_INSTITUTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string ACCOUNT_NUMBER_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ACCOUNT_NUMBER_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_INVALID", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TYPE_IMMUTABLE {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_IMMUTABLE", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_CREATE_CANNOT_USE_EXISTING_AND_NEW_TAB {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_CREATE_CANNOT_USE_EXISTING_AND_NEW_TAB", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_ALREADY_LINKED {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_ALREADY_LINKED", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TERMINAL_ID_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_TERMINAL_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TAB_ID_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_TAB_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TAB_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_TAB_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string ACCOUNT_TAB_ALREADY_LINKED {
            get {
                return ResourceManager.GetString("ACCOUNT_TAB_ALREADY_LINKED", resourceCulture);
            }
        }
        
        public static string OPERATOR_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("OPERATOR_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string OPERATOR_ACCOUNT_ALREADY_ACTIVE {
            get {
                return ResourceManager.GetString("OPERATOR_ACCOUNT_ALREADY_ACTIVE", resourceCulture);
            }
        }
        
        public static string CLIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string CLIENT_ID_EMPTY {
            get {
                return ResourceManager.GetString("CLIENT_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string CLIENT_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CLIENT_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string CLIENT_PHONE_EMPTY {
            get {
                return ResourceManager.GetString("CLIENT_PHONE_EMPTY", resourceCulture);
            }
        }
        
        public static string CLIENT_PHONE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("CLIENT_PHONE_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string CLIENT_CPF_INVALID {
            get {
                return ResourceManager.GetString("CLIENT_CPF_INVALID", resourceCulture);
            }
        }
        
        public static string CLIENT_CPF_CONFLICT {
            get {
                return ResourceManager.GetString("CLIENT_CPF_CONFLICT", resourceCulture);
            }
        }
        
        public static string TRANSACTION_TYPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string TRANSACTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRANSACTION_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string TRANSACTION_REQUIRES_TAB_ACCOUNT_AND_CLIENT {
            get {
                return ResourceManager.GetString("TRANSACTION_REQUIRES_TAB_ACCOUNT_AND_CLIENT", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DATE_LOCKED {
            get {
                return ResourceManager.GetString("TRANSACTION_DATE_LOCKED", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_ACCOUNT_OUT_OF_SCOPE {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_ACCOUNT_OUT_OF_SCOPE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_VALUE_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("TRANSACTION_VALUE_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_VALUE_PRECISION_14X2 {
            get {
                return ResourceManager.GetString("TRANSACTION_VALUE_PRECISION_14X2", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TRANSACTION_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DUE_DATE_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_DUE_DATE_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DUE_DATE_BEFORE_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_DUE_DATE_BEFORE_DATE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_PAID_AT_BEFORE_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_PAID_AT_BEFORE_DATE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_CANNOT_UPDATE_CANCELLED {
            get {
                return ResourceManager.GetString("TRANSACTION_CANNOT_UPDATE_CANCELLED", resourceCulture);
            }
        }
        
        public static string TRANSACTION_CANNOT_FINALIZE_NON_DRAFT {
            get {
                return ResourceManager.GetString("TRANSACTION_CANNOT_FINALIZE_NON_DRAFT", resourceCulture);
            }
        }

        public static string TRANSACTION_ALREADY_CANCELLED {
            get {
                return ResourceManager.GetString("TRANSACTION_ALREADY_CANCELLED", resourceCulture);
            }
        }

        public static string TRANSACTION_CANCELLATION_REASON_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_CANCELLATION_REASON_EMPTY", resourceCulture);
            }
        }

        public static string TRANSACTION_CANCELLATION_REASON_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TRANSACTION_CANCELLATION_REASON_MAX_LENGTH", resourceCulture);
            }
        }

        public static string TRANSACTION_FIADO_REQUIRES_CLIENT {
            get {
                return ResourceManager.GetString("TRANSACTION_FIADO_REQUIRES_CLIENT", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_NOT_RECORDING_OPERATOR {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_NOT_RECORDING_OPERATOR", resourceCulture);
            }
        }
        
        public static string TRANSACTION_UPDATE_REQUIRES_SAME_DAY {
            get {
                return ResourceManager.GetString("TRANSACTION_UPDATE_REQUIRES_SAME_DAY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_CANNOT_OVERRIDE_RECORDED_BY_OPERATOR {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_CANNOT_OVERRIDE_RECORDED_BY_OPERATOR", resourceCulture);
            }
        }
        
        public static string TRANSACTION_MEMBER_REQUIRES_OPERATOR_LINK {
            get {
                return ResourceManager.GetString("TRANSACTION_MEMBER_REQUIRES_OPERATOR_LINK", resourceCulture);
            }
        }
        
        public static string TRANSACTION_REQUIRES_RECORDED_BY_OPERATOR {
            get {
                return ResourceManager.GetString("TRANSACTION_REQUIRES_RECORDED_BY_OPERATOR", resourceCulture);
            }
        }
        
        public static string TRANSACTION_CHEQUE_REQUIRES_DUE_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_CHEQUE_REQUIRES_DUE_DATE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_COUNT_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_COUNT_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_REQUIRES_CHEQUE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_REQUIRES_CHEQUE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_AUTO_GENERATE_CANNOT_HAVE_ITEMS {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_AUTO_GENERATE_CANNOT_HAVE_ITEMS", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_TOTAL_MISMATCH {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_TOTAL_MISMATCH", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_DUE_DATES_MUST_INCREASE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_DUE_DATES_MUST_INCREASE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_FIRST_DUE_DATE_MUST_BE_FUTURE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_FIRST_DUE_DATE_MUST_BE_FUTURE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_INSTALLMENT_ROW_VALUE_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("TRANSACTION_INSTALLMENT_ROW_VALUE_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        public static string TRANSACTION_DATE_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_DATE_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_TYPE_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_ACCOUNT_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_ACCOUNT_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_RECORDED_BY_OPERATOR_ID_EMPTY {
            get {
                return ResourceManager.GetString("TRANSACTION_RECORDED_BY_OPERATOR_ID_EMPTY", resourceCulture);
            }
        }
        
        public static string TRANSACTION_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_PAGE_INVALID", resourceCulture);
            }
        }
        
        public static string TRANSACTION_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }
        
        public static string TRANSACTION_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }

        public static string TRANSACTION_LIST_MINE_AND_OPERATOR_ID_CONFLICT {
            get {
                return ResourceManager.GetString("TRANSACTION_LIST_MINE_AND_OPERATOR_ID_CONFLICT", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_FOUND {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_FOUND", resourceCulture);
            }
        }

        public static string DAILYCLOSE_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_DATE_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ACCOUNT_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ACCOUNT_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LOCK_DATE_VIOLATION {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LOCK_DATE_VIOLATION", resourceCulture);
            }
        }

        public static string DAILYCLOSE_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("DAILYCLOSE_DATE_CONFLICT", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_DUPLICATE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_DUPLICATE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_EDITABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_EDITABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_SUBMITTABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_SUBMITTABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_APPROVABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_APPROVABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_NOT_REJECTABLE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_NOT_REJECTABLE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_REJECTION_REASON_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_REJECTION_REASON_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_REJECTION_REASON_LENGTH {
            get {
                return ResourceManager.GetString("DAILYCLOSE_REJECTION_REASON_LENGTH", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_PRODUCT_FORBIDDEN {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_PRODUCT_FORBIDDEN", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_VALUE_NEGATIVE {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_VALUE_NEGATIVE", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_VALUE_PRECISION {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_VALUE_PRECISION", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEMS_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEMS_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_PRODUCT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_PRODUCT_ID_REQUIRED", resourceCulture);
            }
        }

        public static string DAILYCLOSE_ITEM_PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DAILYCLOSE_ITEM_PRODUCT_NOT_FOUND", resourceCulture);
            }
        }

        public static string DAILYCLOSE_BRANCH_MISMATCH {
            get {
                return ResourceManager.GetString("DAILYCLOSE_BRANCH_MISMATCH", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_PAGE_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }

        public static string DAILYCLOSE_LIST_MINE_AND_OPERATOR_ID_CONFLICT {
            get {
                return ResourceManager.GetString("DAILYCLOSE_LIST_MINE_AND_OPERATOR_ID_CONFLICT", resourceCulture);
            }
        }

        public static string TIMEENTRY_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("TIMEENTRY_DATE_CONFLICT", resourceCulture);
            }
        }

        public static string TIMEENTRY_NOT_FOUND {
            get {
                return ResourceManager.GetString("TIMEENTRY_NOT_FOUND", resourceCulture);
            }
        }

        public static string TIMEENTRY_ID_EMPTY {
            get {
                return ResourceManager.GetString("TIMEENTRY_ID_EMPTY", resourceCulture);
            }
        }

        public static string TIMEENTRY_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("TIMEENTRY_DATE_REQUIRED", resourceCulture);
            }
        }

        public static string TIMEENTRY_STATUS_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_STATUS_INVALID", resourceCulture);
            }
        }

        public static string TIMEENTRY_OPERATOR_ID_REQUIRED {
            get {
                return ResourceManager.GetString("TIMEENTRY_OPERATOR_ID_REQUIRED", resourceCulture);
            }
        }

        public static string TIMEENTRY_NOT_OWN_OPERATOR {
            get {
                return ResourceManager.GetString("TIMEENTRY_NOT_OWN_OPERATOR", resourceCulture);
            }
        }

        public static string TIMEENTRY_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_LIST_PAGE_INVALID", resourceCulture);
            }
        }

        public static string TIMEENTRY_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("TIMEENTRY_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string HOLIDAY_DATE_CONFLICT {
            get {
                return ResourceManager.GetString("HOLIDAY_DATE_CONFLICT", resourceCulture);
            }
        }

        public static string HOLIDAY_NOT_FOUND {
            get {
                return ResourceManager.GetString("HOLIDAY_NOT_FOUND", resourceCulture);
            }
        }

        public static string HOLIDAY_ID_EMPTY {
            get {
                return ResourceManager.GetString("HOLIDAY_ID_EMPTY", resourceCulture);
            }
        }

        public static string HOLIDAY_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("HOLIDAY_DATE_REQUIRED", resourceCulture);
            }
        }

        public static string HOLIDAY_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("HOLIDAY_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }

        public static string HOLIDAY_LIST_PAGE_INVALID {
            get {
                return ResourceManager.GetString("HOLIDAY_LIST_PAGE_INVALID", resourceCulture);
            }
        }

        public static string HOLIDAY_LIST_PAGE_SIZE_INVALID {
            get {
                return ResourceManager.GetString("HOLIDAY_LIST_PAGE_SIZE_INVALID", resourceCulture);
            }
        }

        public static string HOLIDAY_CREATE_BATCH_EMPTY {
            get {
                return ResourceManager.GetString("HOLIDAY_CREATE_BATCH_EMPTY", resourceCulture);
            }
        }

        public static string HOLIDAY_LIST_DATE_RANGE_INVALID {
            get {
                return ResourceManager.GetString("HOLIDAY_LIST_DATE_RANGE_INVALID", resourceCulture);
            }
        }
    }
}
