//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("server.Exceptions.ResourcesErrorMessages", typeof(ResourcesErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }

        public static string BRANCH_CNPJ_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_CNPJ_MAX_LENGTH", resourceCulture);
            }
        }

        public static string BRANCH_ID_EMPTY {
            get {
                return ResourceManager.GetString("BRANCH_ID_EMPTY", resourceCulture);
            }
        }

        public static string BRANCH_USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("BRANCH_USER_ID_EMPTY", resourceCulture);
            }
        }

        public static string BRANCH_USER_ALREADY_ACTIVE {
            get {
                return ResourceManager.GetString("BRANCH_USER_ALREADY_ACTIVE", resourceCulture);
            }
        }

        public static string BRANCH_USER_LAST_ADMIN_CONFLICT {
            get {
                return ResourceManager.GetString("BRANCH_USER_LAST_ADMIN_CONFLICT", resourceCulture);
            }
        }

        public static string BRANCH_USER_IDENTIFIER_EXCLUSIVE {
            get {
                return ResourceManager.GetString("BRANCH_USER_IDENTIFIER_EXCLUSIVE", resourceCulture);
            }
        }

        public static string BRANCH_USER_IDENTIFIER_REQUIRED {
            get {
                return ResourceManager.GetString("BRANCH_USER_IDENTIFIER_REQUIRED", resourceCulture);
            }
        }

        public static string BRANCH_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("BRANCH_USER_NOT_FOUND", resourceCulture);
            }
        }

        public static string BRANCH_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_NAME_MAX_LENGTH", resourceCulture);
            }
        }

        public static string BRANCH_NOT_FOUND {
            get {
                return ResourceManager.GetString("BRANCH_NOT_FOUND", resourceCulture);
            }
        }

        public static string BRANCH_PHONE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("BRANCH_PHONE_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        public static string ROLE_INVALID {
            get {
                return ResourceManager.GetString("ROLE_INVALID", resourceCulture);
            }
        }

        public static string ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("ROLE_REQUIRED", resourceCulture);
            }
        }

        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }

        public static string USER_ID_EMPTY {
            get {
                return ResourceManager.GetString("USER_ID_EMPTY", resourceCulture);
            }
        }

        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }

        public static string EMAIL_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_NOT_REGISTERED", resourceCulture);
            }
        }
        
        public static string PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("PASSWORD_WRONG", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_INVALID {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_INVALID", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string REFRESHTOKEN_WITHOUT_USER {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_WITHOUT_USER", resourceCulture);
            }
        }
        
        public static string TOKEN_EMPTY {
            get {
                return ResourceManager.GetString("TOKEN_EMPTY", resourceCulture);
            }
        }
        
        public static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string TOKEN_WITHOUT_USER {
            get {
                return ResourceManager.GetString("TOKEN_WITHOUT_USER", resourceCulture);
            }
        }
        
        public static string TOKEN_WITHOUT_PERMISSION {
            get {
                return ResourceManager.GetString("TOKEN_WITHOUT_PERMISSION", resourceCulture);
            }
        }

        public static string OPERATOR_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("OPERATOR_NAME_MAX_LENGTH", resourceCulture);
            }
        }

        public static string OPERATOR_USER_NOT_BRANCH_MEMBER {
            get {
                return ResourceManager.GetString("OPERATOR_USER_NOT_BRANCH_MEMBER", resourceCulture);
            }
        }

        public static string OPERATOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("OPERATOR_NOT_FOUND", resourceCulture);
            }
        }
    }
}
