using System.Globalization;
using CommonTestUtilities.Entities;
using CommonTestUtilities.Repositories;
using CommonTestUtilities.Requests;
using CommonTestUtilities.Services;
using NSubstitute;
using server.Application.Services.Holidays;
using server.Application.Services.Members;
using server.Application.Services.Settings;
using server.Application.Services.Transactions;
using server.Application.UseCases.Transactions.InstallmentPreview;
using server.Communication.Requests;
using server.Domain.Entities;
using server.Domain.Entities.Enums;
using server.Domain.Interfaces;
using server.Exceptions;
using server.Exceptions.Exceptions;
using Shouldly;
using Xunit;

namespace UseCases.Test.UseCases.Transactions.InstallmentPreview;

public class PreviewInstallmentPlanUseCaseTest
{
    [Fact]
    public async Task Execute_ShouldReturnPreviewWithCorrectShapeForManualInstallments()
    {
        var firstDueDate = DateTime.Today.AddDays(30);
        var ctx = BuildHappyPathContext(SettlementRule.OperatorEnteredCheque);
        ctx.Request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithDate(DateTime.Today)
            .WithDescription("Cheque do cliente")
            .WithValue(333.33m)
            .WithTransactionTypeId(ctx.Request.TransactionTypeId)
            .WithAccountId(ctx.Request.AccountId)
            .WithInstallments(
            [
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate, Value = 100.01m },
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate.AddDays(13), Value = 111.11m },
                new RequestCreateTransactionInstallmentItemJson { DueDate = firstDueDate.AddDays(40), Value = 122.21m }
            ])
            .Build();

        var useCase = CreateUseCase(ctx);
        var response = await useCase.Execute(ctx.Request);

        response.TotalValue.ShouldBe(333.33m);
        response.InstallmentCount.ShouldBe(3);
        response.Rows.Count.ShouldBe(3);

        for (var i = 0; i < 3; i++)
        {
            response.Rows[i].Index.ShouldBe(i + 1);
            response.Rows[i].Value.ShouldBe(ctx.Request.Installments[i].Value);
            response.Rows[i].DueDate.ShouldBe(ctx.Request.Installments[i].DueDate);
            response.Rows[i].Description.ShouldBe($"CH PRE ({i + 1}/3) - Cheque do cliente");
        }
    }

    [Theory]
    [InlineData(2, "100.00")]
    [InlineData(3, "333.33")]
    [InlineData(12, "1000.00")]
    public async Task Execute_ShouldReturnPreviewWithCorrectShapeForAutoGeneratedInstallments(
        int installmentCount,
        string totalText)
    {
        var total = decimal.Parse(totalText, CultureInfo.InvariantCulture);
        var baseDueDate = DateTime.Today.AddDays(30);
        var ctx = BuildHappyPathContext(SettlementRule.OperatorEnteredCheque);
        ctx.Request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithDate(DateTime.Today)
            .WithDescription(null)
            .WithValue(total)
            .WithTransactionTypeId(ctx.Request.TransactionTypeId)
            .WithAccountId(ctx.Request.AccountId)
            .WithAutoGeneration(installmentCount, baseDueDate)
            .Build();

        var useCase = CreateUseCase(ctx);
        var response = await useCase.Execute(ctx.Request);

        response.InstallmentCount.ShouldBe(installmentCount);
        response.Rows.Count.ShouldBe(installmentCount);
        response.TotalValue.ShouldBe(total);
        response.Rows.Sum(r => r.Value).ShouldBe(total);

        for (var i = 0; i < installmentCount; i++)
        {
            response.Rows[i].Index.ShouldBe(i + 1);
            response.Rows[i].DueDate.ShouldBe(DueDateCalculator.AdjustToNextBusinessDay(baseDueDate.AddMonths(i)));
            response.Rows[i].Description.ShouldBe($"CH PRE ({i + 1}/{installmentCount})");
        }
    }

    [Fact]
    public async Task Execute_ShouldThrowOnValidationException_WhenRequestIsInvalid()
    {
        var ctx = BuildHappyPathContext(SettlementRule.OperatorEnteredCheque);
        ctx.Request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithValue(0m)
            .Build();

        var useCase = CreateUseCase(ctx);

        await Should.ThrowAsync<OnValidationException>(() => useCase.Execute(ctx.Request));
    }

    [Fact]
    public async Task Execute_ShouldThrowConflictException_WhenTransactionTypeIsNotOperatorEnteredCheque()
    {
        var ctx = BuildHappyPathContext(SettlementRule.SameDay);

        var useCase = CreateUseCase(ctx);

        var exception = await Should.ThrowAsync<ConflictException>(() => useCase.Execute(ctx.Request));
        exception.Message.ShouldBe(ResourcesErrorMessages.TRANSACTION_INSTALLMENT_REQUIRES_CHEQUE);
    }

    private static PreviewInstallmentPlanUseCase CreateUseCase(HappyPathContext ctx)
    {
        var recordedByOperatorResolver = new TransactionRecordedByOperatorResolver();
        var branchConsistencyService = new TransactionBranchConsistencyService(
            ctx.AccountsRepository,
            ctx.OperatorsRepository,
            ctx.ClientsRepository,
            ctx.TransactionTypesRepository);
        var lockDateGuard = new LockDateGuard(ctx.SettingsRepository);
        var memberAccountScopeResolver = new MemberAccountScopeResolver(
            ctx.OperatorsRepository,
            ctx.OperatorAccountsRepository);
        var memberAccountScopeGuard = new MemberAccountScopeGuard();
        var transactionCreatePreamble = new TransactionCreatePreamble(
            ctx.AuthenticationService,
            memberAccountScopeResolver,
            recordedByOperatorResolver,
            branchConsistencyService,
            memberAccountScopeGuard,
            lockDateGuard,
            ctx.BranchHolidaySource);
        var installmentPlanBuilder = new InstallmentPlanBuilder();

        return new PreviewInstallmentPlanUseCase(transactionCreatePreamble, installmentPlanBuilder);
    }

    private static HappyPathContext BuildHappyPathContext(SettlementRule settlementRule)
    {
        var branchUser = new BranchUserBuilder().WithRole(Role.Manager).Build();
        var callerOperator = new OperatorBuilder()
            .WithBranchId(branchUser.BranchId)
            .WithUserId(branchUser.UserId)
            .Build();
        var accountId = Guid.NewGuid();
        var account = new AccountBuilder()
            .WithId(accountId)
            .WithBranchId(branchUser.BranchId)
            .WithType(AccountType.Terminal)
            .Build();

        var branch = new BranchBuilder().WithId(branchUser.BranchId).Build();
        var category = new Category
        {
            Id = Guid.NewGuid(),
            Name = "Saídas",
            DefaultDirection = Direction.Out,
            BranchId = branchUser.BranchId,
            Branch = branch
        };
        var transactionType = new TransactionTypeBuilder()
            .WithCategory(category)
            .WithSettlementRule(settlementRule)
            .WithRequiresTabAccountAndClient(false)
            .Build();

        var operatorAccount = new OperatorAccountBuilder()
            .WithOperator(callerOperator)
            .WithAccount(account)
            .Build();

        var request = new RequestCreateTransactionInstallmentJsonBuilder()
            .WithTransactionTypeId(transactionType.Id)
            .WithAccountId(accountId)
            .Build();

        var authenticationService = new AuthenticationServiceBuilder()
            .GetAuthenticatedBranchUser(branchUser)
            .Build();
        var operatorsRepository = new OperatorsRepositoryBuilder()
            .GetActiveLinkedByUserIdAndBranchIdAsNoTracking(branchUser.UserId, branchUser.BranchId, callerOperator)
            .GetActiveByIdAndBranchIdAsNoTracking(callerOperator.Id, branchUser.BranchId, callerOperator)
            .Build();
        var accountsRepository = new AccountsRepositoryBuilder()
            .GetActiveByIdAndBranchIdAsNoTracking(accountId, branchUser.BranchId, account)
            .Build();
        var clientsRepository = new ClientsRepositoryBuilder().Build();
        var transactionTypesRepository = new TransactionTypesRepositoryBuilder()
            .GetActiveByIdAndBranchIdWithCategoryAsNoTrackingReturns(transactionType.Id, branchUser.BranchId, transactionType)
            .Build();
        var settingsRepository = new SettingsRepositoryBuilder()
            .GetByBranchIdAsNoTrackingReturns(branchUser.BranchId, null)
            .Build();
        var operatorAccountsRepository = new OperatorAccountsRepositoryBuilder()
            .ListActiveByOperatorIdAsNoTracking(callerOperator.Id, [operatorAccount])
            .Build();
        var branchHolidaySource = Substitute.For<IBranchHolidaySource>();
        branchHolidaySource.GetHolidayDatesAsync(branchUser.BranchId).Returns(new HashSet<DateOnly>());

        return new HappyPathContext
        {
            BranchUser = branchUser,
            CallerOperator = callerOperator,
            Account = account,
            TransactionType = transactionType,
            Request = request,
            AuthenticationService = authenticationService,
            OperatorsRepository = operatorsRepository,
            AccountsRepository = accountsRepository,
            ClientsRepository = clientsRepository,
            TransactionTypesRepository = transactionTypesRepository,
            SettingsRepository = settingsRepository,
            OperatorAccountsRepository = operatorAccountsRepository,
            BranchHolidaySource = branchHolidaySource
        };
    }

    private class HappyPathContext
    {
        public required BranchUser BranchUser { get; set; }
        public required Operator CallerOperator { get; set; }
        public required Account Account { get; set; }
        public required TransactionType TransactionType { get; set; }
        public required RequestCreateTransactionInstallmentJson Request { get; set; }
        public required IAuthenticationService AuthenticationService { get; set; }
        public required IOperatorsRepository OperatorsRepository { get; set; }
        public required IAccountsRepository AccountsRepository { get; set; }
        public required IClientsRepository ClientsRepository { get; set; }
        public required ITransactionTypesRepository TransactionTypesRepository { get; set; }
        public required ISettingsRepository SettingsRepository { get; set; }
        public required IOperatorAccountsRepository OperatorAccountsRepository { get; set; }
        public required IBranchHolidaySource BranchHolidaySource { get; set; }
    }
}
