using System.Text;
using System.Text.Json;

namespace WebApi.Test.OpenApi;

/// <summary>
/// Projects the generated OpenAPI document onto the contract surface Milestone 7.6 owns:
/// required vs optional schema members and operation parameters, and named string enums.
///
/// The projection is deliberately lossy so the snapshot stays reviewable as a diff. It drops
/// everything that is either environment-dependent or generator noise: the <c>servers</c> block
/// (the host and port change per run), <c>info</c>, descriptions, summaries, examples, tags,
/// scalar formats and patterns, and the duplicate <c>application/json</c> / <c>text/json</c> /
/// <c>text/plain</c> media-type copies of one schema. Everything that survives is sorted by an
/// ordinal key, so a single contract change produces a single-line diff instead of a reordered file.
/// </summary>
internal static class OpenApiContractSurface
{
    private const string EnumPrefix = "enum:";

    private static readonly string[] HttpMethodOrder =
        ["get", "put", "post", "patch", "delete", "head", "options", "trace"];

    private static readonly string[] ParameterLocationOrder = ["path", "query", "header", "cookie"];

    private static readonly string[] HeaderLines =
    [
        "# OpenAPI contract surface snapshot (Milestone 7.6).",
        "#",
        "# Pins the two systemic guarantees the hardening milestone owns:",
        "#   1. required vs optional members and operation parameters, derived from C# nullability;",
        "#   2. named string enums, never bare numeric enum values.",
        "#",
        "# Generated by OpenApiContractSurface.Render from the live /openapi/v1.json document.",
        "# Environment-dependent and generator-noise fields (servers, info, descriptions, examples,",
        "# formats, patterns, duplicate media types) are excluded, and every list is ordinally sorted.",
        "# A trailing '?' marks a schema that also accepts null.",
        "#",
        "# Regenerate: run OpenApiContractSurfaceSnapshotTest, review the emitted",
        "# openapi-contract-surface.received.txt diff, then replace this file with it."
    ];

    internal static string Render(JsonElement document)
    {
        var builder = new StringBuilder();
        foreach (var line in HeaderLines)
            builder.Append(line).Append('\n');

        builder.Append('\n').Append("openapi ").Append(document.GetProperty("openapi").GetString()).Append('\n');

        var schemas = document.GetProperty("components").GetProperty("schemas");
        var enumComponents = EnumComponentNames(schemas);

        AppendEnums(builder, schemas, enumComponents);
        AppendSchemas(builder, schemas, enumComponents);
        AppendOperations(builder, document.GetProperty("paths"), enumComponents);

        return builder.ToString();
    }

    private static HashSet<string> EnumComponentNames(JsonElement schemas) =>
        schemas.EnumerateObject()
            .Where(schema => schema.Value.TryGetProperty("enum", out _))
            .Select(schema => schema.Name)
            .ToHashSet(StringComparer.Ordinal);

    private static void AppendEnums(StringBuilder builder, JsonElement schemas, HashSet<string> enumComponents)
    {
        builder.Append('\n').Append("## enums").Append('\n');
        foreach (var name in enumComponents.OrderBy(name => name, StringComparer.Ordinal))
        {
            var schema = schemas.GetProperty(name);
            var declaredTypes = TypeNames(schema);
            var type = declaredTypes.Count == 0 ? "(untyped)" : string.Join("|", declaredTypes);
            var values = schema.GetProperty("enum").EnumerateArray().Select(RawValue);
            builder.Append("enum ").Append(name).Append(' ').Append(type).Append(": ")
                .Append(string.Join(", ", values)).Append('\n');
        }
    }

    private static void AppendSchemas(StringBuilder builder, JsonElement schemas, HashSet<string> enumComponents)
    {
        builder.Append('\n').Append("## schemas").Append('\n');
        foreach (var schema in schemas.EnumerateObject()
                     .Where(candidate => enumComponents.Contains(candidate.Name) is false)
                     .OrderBy(candidate => candidate.Name, StringComparer.Ordinal))
        {
            builder.Append('\n').Append("schema ").Append(schema.Name).Append('\n');
            var required = schema.Value.TryGetProperty("required", out var requiredElement)
                ? requiredElement.EnumerateArray().Select(member => member.GetString()!).ToHashSet(StringComparer.Ordinal)
                : [];

            if (schema.Value.TryGetProperty("properties", out var properties) is false)
            {
                builder.Append("  (no properties)").Append('\n');
                continue;
            }

            foreach (var property in properties.EnumerateObject()
                         .OrderBy(property => property.Name, StringComparer.Ordinal))
            {
                builder.Append("  ").Append(property.Name).Append(' ')
                    .Append(required.Contains(property.Name) ? "required" : "optional").Append(' ')
                    .Append(TypeToken(property.Value, enumComponents))
                    .Append('\n');
                required.Remove(property.Name);
            }

            // A required entry with no matching property would mean the schema transformer wrote a CLR
            // member name instead of the System.Text.Json name. Keep it visible instead of dropping it.
            foreach (var orphan in required.OrderBy(member => member, StringComparer.Ordinal))
                builder.Append("  ").Append(orphan).Append(" required-without-property").Append('\n');
        }
    }

    private static void AppendOperations(StringBuilder builder, JsonElement paths, HashSet<string> enumComponents)
    {
        builder.Append('\n').Append("## operations").Append('\n');
        foreach (var path in paths.EnumerateObject().OrderBy(path => path.Name, StringComparer.Ordinal))
        {
            foreach (var method in HttpMethodOrder)
            {
                if (path.Value.TryGetProperty(method, out var operation) is false)
                    continue;

                builder.Append('\n').Append("operation ").Append(method.ToUpperInvariant()).Append(' ')
                    .Append(path.Name).Append('\n');
                AppendParameters(builder, operation, enumComponents);
                AppendRequestBody(builder, operation, enumComponents);
                AppendResponses(builder, operation, enumComponents);
            }
        }
    }

    private static void AppendParameters(StringBuilder builder, JsonElement operation, HashSet<string> enumComponents)
    {
        if (operation.TryGetProperty("parameters", out var parameters) is false)
            return;

        var rows = parameters.EnumerateArray()
            .Select(parameter =>
            {
                var location = parameter.GetProperty("in").GetString()!;
                var name = parameter.GetProperty("name").GetString()!;
                var required = parameter.TryGetProperty("required", out var requiredElement) &&
                               requiredElement.GetBoolean();
                var row = new StringBuilder("  ").Append(location).Append(' ').Append(name).Append(' ')
                    .Append(required ? "required" : "optional");
                if (parameter.TryGetProperty("schema", out var schema))
                {
                    row.Append(' ').Append(TypeToken(schema, enumComponents));
                    if (schema.TryGetProperty("default", out var defaultValue))
                        row.Append(" default=").Append(defaultValue.GetRawText());
                }

                return (Rank: Array.IndexOf(ParameterLocationOrder, location), Name: name, Row: row.ToString());
            })
            .OrderBy(row => row.Rank)
            .ThenBy(row => row.Name, StringComparer.Ordinal);

        foreach (var row in rows)
            builder.Append(row.Row).Append('\n');
    }

    private static void AppendRequestBody(StringBuilder builder, JsonElement operation, HashSet<string> enumComponents)
    {
        if (operation.TryGetProperty("requestBody", out var requestBody) is false)
            return;

        var required = requestBody.TryGetProperty("required", out var requiredElement) && requiredElement.GetBoolean();
        builder.Append("  body ").Append(required ? "required" : "optional").Append(' ')
            .Append(ContentTypeToken(requestBody, enumComponents)).Append('\n');
    }

    private static void AppendResponses(StringBuilder builder, JsonElement operation, HashSet<string> enumComponents)
    {
        if (operation.TryGetProperty("responses", out var responses) is false)
            return;

        foreach (var response in responses.EnumerateObject()
                     .OrderBy(response => response.Name, StringComparer.Ordinal))
        {
            builder.Append("  response ").Append(response.Name).Append(' ')
                .Append(ContentTypeToken(response.Value, enumComponents));

            if (response.Value.TryGetProperty("headers", out var headers))
            {
                var names = headers.EnumerateObject()
                    .Select(header => header.Name)
                    .OrderBy(name => name, StringComparer.Ordinal);
                builder.Append(" headers=").Append(string.Join(",", names));
            }

            builder.Append('\n');
        }
    }

    /// <summary>
    /// Collapses the generator's per-media-type schema copies. Identical copies render once; a real
    /// divergence renders every media type so it cannot hide behind the collapse.
    /// </summary>
    private static string ContentTypeToken(JsonElement carrier, HashSet<string> enumComponents)
    {
        if (carrier.TryGetProperty("content", out var content) is false)
            return "(no content)";

        var byMediaType = content.EnumerateObject()
            .OrderBy(media => media.Name, StringComparer.Ordinal)
            .Select(media => (
                MediaType: media.Name,
                Schema: media.Value.TryGetProperty("schema", out var schema)
                    ? TypeToken(schema, enumComponents)
                    : "(no schema)"))
            .ToList();

        var distinct = byMediaType.Select(media => media.Schema).Distinct(StringComparer.Ordinal).ToList();
        return distinct.Count == 1
            ? distinct[0]
            : string.Join(", ", byMediaType.Select(media => $"{media.MediaType}:{media.Schema}"));
    }

    /// <summary>
    /// Renders one schema as a single stable token: the referenced component name (prefixed with
    /// <c>enum:</c> for a named enum component), an element token plus <c>[]</c> for arrays, the
    /// JSON type otherwise, and a trailing <c>?</c> whenever null is also accepted.
    /// </summary>
    private static string TypeToken(JsonElement schema, HashSet<string> enumComponents)
    {
        if (schema.ValueKind != JsonValueKind.Object)
            return "(inline)";

        if (ReferenceName(schema) is { } reference)
            return enumComponents.Contains(reference) ? EnumPrefix + reference : reference;

        if (schema.TryGetProperty("oneOf", out var oneOf))
        {
            var branches = oneOf.EnumerateArray().ToList();
            var nullable = branches.Any(IsNullSchema);
            var tokens = branches
                .Where(branch => IsNullSchema(branch) is false)
                .Select(branch => TypeToken(branch, enumComponents))
                .OrderBy(token => token, StringComparer.Ordinal)
                .ToList();
            return string.Join("|", tokens) + (nullable ? "?" : string.Empty);
        }

        // An inline enum would bypass the reusable named-enum component contract entirely; surface it.
        if (schema.TryGetProperty("enum", out var inline))
        {
            return EnumPrefix + "inline[" +
                   string.Join(",", inline.EnumerateArray().Select(RawValue)) + "]";
        }

        var types = TypeNames(schema);
        var acceptsNull = types.Remove("null");
        var baseToken = types switch
        {
            { Count: 0 } => "(untyped)",
            _ when types.Contains("array") => ArrayToken(schema, types, enumComponents),
            _ => string.Join("|", types)
        };

        return baseToken + (acceptsNull ? "?" : string.Empty);
    }

    private static string ArrayToken(JsonElement schema, List<string> types, HashSet<string> enumComponents)
    {
        var element = schema.TryGetProperty("items", out var items)
            ? TypeToken(items, enumComponents)
            : "(untyped)";
        var others = types.Where(type => type != "array").ToList();
        return others.Count == 0
            ? element + "[]"
            : string.Join("|", others.Append(element + "[]"));
    }

    private static List<string> TypeNames(JsonElement schema)
    {
        if (schema.TryGetProperty("type", out var type) is false)
            return [];

        return type.ValueKind == JsonValueKind.Array
            ? type.EnumerateArray().Select(value => value.GetString()!).OrderBy(value => value, StringComparer.Ordinal).ToList()
            : [type.GetString()!];
    }

    private static bool IsNullSchema(JsonElement schema) =>
        schema.ValueKind == JsonValueKind.Object &&
        schema.TryGetProperty("type", out var type) &&
        type.ValueKind == JsonValueKind.String &&
        type.GetString() == "null";

    private static string? ReferenceName(JsonElement schema) =>
        schema.ValueKind == JsonValueKind.Object && schema.TryGetProperty("$ref", out var reference)
            ? reference.GetString()?.Split('/')[^1]
            : null;

    private static string RawValue(JsonElement value) =>
        value.ValueKind == JsonValueKind.String ? value.GetString()! : value.GetRawText();
}
