<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <RootNamespace>server</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\server.Application\server.Application.csproj" />
      <ProjectReference Include="..\server.Communication\server.Communication.csproj" />
      <ProjectReference Include="..\server.Exceptions\server.Exceptions.csproj" />
      <ProjectReference Include="..\server.Infrastructure\server.Infrastructure.csproj" />
    </ItemGroup>

</Project>
