using server.Communication.Requests;
using server.Exceptions;
using server.Exceptions.Exceptions;

namespace server.Application.Services.Transactions;

public sealed record InstallmentPlanRow(
    Guid Id,
    Guid OriginTransactionId,
    Guid BranchId,
    decimal Value,
    DateTime DueDate,
    string Description);

public class InstallmentPlanBuilder
{
    public IReadOnlyList<InstallmentPlanRow> Build(
        RequestCreateTransactionInstallmentJson request,
        Guid branchId,
        Guid originTransactionId,
        IReadOnlySet<DateOnly>? holidayDates = null)
    {
        return request.AutoGenerateInstallments
            ? BuildAutoGeneratedInstallmentPlan(request, branchId, originTransactionId, holidayDates)
            : BuildManualInstallmentPlan(request, branchId, originTransactionId);
    }

    private static List<InstallmentPlanRow> BuildManualInstallmentPlan(
        RequestCreateTransactionInstallmentJson request,
        Guid branchId,
        Guid originTransactionId)
    {
        var rows = request.Installments
            .Select((installment, index) => new InstallmentPlanRow(
                Id: index == 0 ? originTransactionId : Guid.NewGuid(),
                OriginTransactionId: originTransactionId,
                BranchId: branchId,
                Value: installment.Value,
                DueDate: installment.DueDate,
                Description: BuildDescription(request.Description, index + 1, request.Installments.Count)))
            .ToList();

        EnsureAllInstallmentValuesPositive(rows);
        return rows;
    }

    private static List<InstallmentPlanRow> BuildAutoGeneratedInstallmentPlan(
        RequestCreateTransactionInstallmentJson request,
        Guid branchId,
        Guid originTransactionId,
        IReadOnlySet<DateOnly>? holidayDates)
    {
        var n = request.InstallmentCount!.Value;
        var total = request.Value;
        var perInstallment = Math.Round(total / n, 2, MidpointRounding.AwayFromZero);
        var residualRow = total - perInstallment * (n - 1);
        var rows = new List<InstallmentPlanRow>(n);

        for (var i = 1; i <= n; i++)
        {
            var isLast = i == n;
            var rowValue = isLast ? residualRow : perInstallment;
            var rowDueDate = DueDateCalculator.AdjustToNextBusinessDay(request.DueDate!.Value.AddMonths(i - 1), holidayDates);

            rows.Add(new InstallmentPlanRow(
                Id: i == 1 ? originTransactionId : Guid.NewGuid(),
                OriginTransactionId: originTransactionId,
                BranchId: branchId,
                Value: rowValue,
                DueDate: rowDueDate,
                Description: BuildDescription(request.Description, i, n)));
        }

        EnsureAllInstallmentValuesPositive(rows);
        return rows;
    }

    private static string BuildDescription(string? operatorDescription, int installmentNumber, int installmentCount)
    {
        var prefix = $"CH PRE ({installmentNumber}/{installmentCount})";

        return string.IsNullOrWhiteSpace(operatorDescription)
            ? prefix
            : $"{prefix} - {operatorDescription.Trim()}";
    }

    private static void EnsureAllInstallmentValuesPositive(IReadOnlyList<InstallmentPlanRow> rows)
    {
        if (rows.All(row => row.Value > 0m))
        {
            return;
        }

        throw new OnValidationException([ResourcesErrorMessages.TRANSACTION_INSTALLMENT_ROW_VALUE_MUST_BE_POSITIVE]);
    }
}
