using Microsoft.Extensions.DependencyInjection;
using server.Application.Services;
using server.Application.Services.DailyCloses;
using server.Application.Services.Holidays;
using server.Application.Services.Operators;
using server.Application.Services.Members;
using server.Application.Services.Settings;
using server.Application.Services.TimeEntries;
using server.Application.Services.Transactions;
using server.Application.UseCases.BranchUsers.Add;
using server.Application.UseCases.BranchUsers.List;
using server.Application.UseCases.BranchUsers.Remove;
using server.Application.UseCases.BranchUsers.UpdateRole;
using server.Application.UseCases.Branches.Create;
using server.Application.UseCases.Branches.CreateSession;
using server.Application.UseCases.Branches.GetCurrentBranchSummary;
using server.Application.UseCases.Branches.ListMyBranches;
using server.Application.UseCases.Accounts.CreateBank;
using server.Application.UseCases.Accounts.CreateTab;
using server.Application.UseCases.Accounts.CreateTerminal;
using server.Application.UseCases.Accounts.Deactivate;
using server.Application.UseCases.Accounts.Get;
using server.Application.UseCases.Accounts.List;
using server.Application.UseCases.Accounts.PairTab;
using server.Application.UseCases.Accounts.UnpairTab;
using server.Application.UseCases.Accounts.Update;
using server.Application.UseCases.OperatorAccounts.AssignAccount;
using server.Application.UseCases.OperatorAccounts.GetOperatorSelfContext;
using server.Application.UseCases.OperatorAccounts.ListOperatorAccounts;
using server.Application.UseCases.OperatorAccounts.SetPrimaryAccount;
using server.Application.UseCases.OperatorAccounts.UnassignAccount;
using server.Application.UseCases.Operators.Create;
using server.Application.UseCases.Operators.Deactivate;
using server.Application.UseCases.Operators.Get;
using server.Application.UseCases.Operators.List;
using server.Application.UseCases.Operators.Update;
using server.Application.UseCases.Clients.Create;
using server.Application.UseCases.Clients.Deactivate;
using server.Application.UseCases.Clients.Get;
using server.Application.UseCases.Clients.List;
using server.Application.UseCases.Clients.Update;
using server.Application.UseCases.Transactions.Cancel;
using server.Application.UseCases.Transactions.Create;
using server.Application.UseCases.Transactions.CreateInstallment;
using server.Application.UseCases.Transactions.Finalize;
using server.Application.UseCases.Transactions.Get;
using server.Application.UseCases.Transactions.List;
using server.Application.UseCases.Transactions.Update;
using server.Application.UseCases.Holidays.Create;
using server.Application.UseCases.Holidays.Deactivate;
using server.Application.UseCases.Holidays.ImportBrazilian;
using server.Application.UseCases.Holidays.List;
using server.Application.UseCases.Holidays.PreviewBrazilianImport;
using server.Application.UseCases.Holidays.Update;
using server.Application.UseCases.TimeEntries.AddSegment;
using server.Application.UseCases.TimeEntries.DeactivateSegment;
using server.Application.UseCases.TimeEntries.Deactivate;
using server.Application.UseCases.TimeEntries.Get;
using server.Application.UseCases.TimeEntries.List;
using server.Application.UseCases.TimeEntries.UpdateSegment;
using server.Application.UseCases.TimeEntries.Upsert;
using server.Application.UseCases.Categories.Create;
using server.Application.UseCases.Categories.Deactivate;
using server.Application.UseCases.Categories.Get;
using server.Application.UseCases.Categories.List;
using server.Application.UseCases.Categories.Update;
using server.Application.UseCases.TransactionTypes.Create;
using server.Application.UseCases.TransactionTypes.Deactivate;
using server.Application.UseCases.TransactionTypes.Get;
using server.Application.UseCases.TransactionTypes.List;
using server.Application.UseCases.TransactionTypes.Update;
using server.Application.UseCases.Products.Create;
using server.Application.UseCases.Products.Deactivate;
using server.Application.UseCases.Products.Get;
using server.Application.UseCases.Products.List;
using server.Application.UseCases.Products.Update;
using server.Application.UseCases.Settings.Get;
using server.Application.UseCases.Settings.Update;
using server.Application.UseCases.DailyCloses.Approve;
using server.Application.UseCases.DailyCloses.Get;
using server.Application.UseCases.DailyCloses.List;
using server.Application.UseCases.DailyCloses.Open;
using server.Application.UseCases.DailyCloses.PutItems;
using server.Application.UseCases.DailyCloses.Reject;
using server.Application.UseCases.DailyCloses.Submit;
using server.Application.UseCases.Users.Login;
using server.Application.UseCases.Users.Register;
using server.Application.UseCases.Users.RenewToken;
using server.Domain.Interfaces;

namespace server.Application;

public static class AppDependencyInjection
{
    public static void AddApplication(this IServiceCollection services)
    {
        services.AddScoped<AddBranchUserUseCase>();
        services.AddScoped<ListBranchUsersUseCase>();
        services.AddScoped<UpdateBranchUserRoleUseCase>();
        services.AddScoped<RemoveBranchUserUseCase>();
        services.AddScoped<CreateBranchUseCase>();
        services.AddScoped<ListMyBranchesUseCase>();
        services.AddScoped<CreateBranchSessionUseCase>();
        services.AddScoped<GetCurrentBranchSummaryUseCase>();
        services.AddScoped<CreateBankAccountUseCase>();
        services.AddScoped<CreateTerminalAccountUseCase>();
        services.AddScoped<CreateTabAccountUseCase>();
        services.AddScoped<ListAccountsUseCase>();
        services.AddScoped<GetAccountUseCase>();
        services.AddScoped<UpdateAccountUseCase>();
        services.AddScoped<PairTabAccountUseCase>();
        services.AddScoped<UnpairTabAccountUseCase>();
        services.AddScoped<DeactivateAccountUseCase>();
        services.AddScoped<AssignAccountUseCase>();
        services.AddScoped<UnassignAccountUseCase>();
        services.AddScoped<SetPrimaryAccountUseCase>();
        services.AddScoped<ListOperatorAccountsUseCase>();
        services.AddScoped<GetOperatorSelfContextUseCase>();
        services.AddScoped<CreateOperatorUseCase>();
        services.AddScoped<ListOperatorsUseCase>();
        services.AddScoped<GetOperatorUseCase>();
        services.AddScoped<UpdateOperatorUseCase>();
        services.AddScoped<DeactivateOperatorUseCase>();
        services.AddScoped<IOperatorUserLinkGuard, OperatorUserLinkGuard>();
        services.AddScoped<CreateCategoryUseCase>();
        services.AddScoped<ListCategoriesUseCase>();
        services.AddScoped<GetCategoryUseCase>();
        services.AddScoped<UpdateCategoryUseCase>();
        services.AddScoped<DeactivateCategoryUseCase>();
        services.AddScoped<CreateTransactionTypeUseCase>();
        services.AddScoped<ListTransactionTypesUseCase>();
        services.AddScoped<GetTransactionTypeUseCase>();
        services.AddScoped<UpdateTransactionTypeUseCase>();
        services.AddScoped<DeactivateTransactionTypeUseCase>();
        services.AddScoped<CreateProductUseCase>();
        services.AddScoped<ListProductsUseCase>();
        services.AddScoped<GetProductUseCase>();
        services.AddScoped<UpdateProductUseCase>();
        services.AddScoped<DeactivateProductUseCase>();
        services.AddScoped<GetSettingUseCase>();
        services.AddScoped<UpdateSettingUseCase>();
        services.AddScoped<CreateClientUseCase>();
        services.AddScoped<ListClientsUseCase>();
        services.AddScoped<GetClientUseCase>();
        services.AddScoped<UpdateClientUseCase>();
        services.AddScoped<DeactivateClientUseCase>();
        services.AddScoped<TransactionRecordedByOperatorResolver>();
        services.AddScoped<TransactionBranchConsistencyService>();
        services.AddScoped<TransactionCreatePreamble>();
        services.AddScoped<InstallmentPlanBuilder>();
        services.AddScoped<DueDateCalculator>();
        services.AddScoped<IBranchClock, BranchClock>();
        services.AddScoped<IMemberAccountScopeResolver, MemberAccountScopeResolver>();
        services.AddScoped<LockDateGuard>();
        services.AddScoped<MemberAccountScopeGuard>();
        services.AddScoped<ITimeEntryCalculationService, TimeEntryCalculationService>();
        services.AddScoped<TimeEntrySegmentMutationService>();
        services.AddScoped<ITimeEntryWritePermissionGuard, TimeEntryWritePermissionGuard>();
        services.AddScoped<IBranchHolidaySource, BranchHolidaySource>();
        services.AddSingleton<IBrazilianHolidayCalendar, BrazilianHolidayCalendar>();
        services.AddSingleton<IBrazilianHolidayCalendarResolver, BrazilianHolidayCalendarResolver>();
        services.AddScoped<IDailyCloseWorkflowGuard, DailyCloseWorkflowGuard>();
        services.AddScoped<ICashVarianceCalculator, CashVarianceCalculator>();
        services.AddScoped<ICashVarianceProductResolver, CashVarianceProductResolver>();
        services.AddScoped<ITransactionMutationPermissionGuard, TransactionMutationPermissionGuard>();
        services.AddScoped<CreateTransactionUseCase>();
        services.AddScoped<CreateTransactionInstallmentUseCase>();
        services.AddScoped<FinalizeTransactionUseCase>();
        services.AddScoped<GetTransactionUseCase>();
        services.AddScoped<ListTransactionsUseCase>();
        services.AddScoped<UpdateTransactionUseCase>();
        services.AddScoped<CancelTransactionUseCase>();
        services.AddScoped<CreateHolidaysUseCase>();
        services.AddScoped<ListHolidaysUseCase>();
        services.AddScoped<UpdateHolidayUseCase>();
        services.AddScoped<DeactivateHolidayUseCase>();
        services.AddScoped<PreviewBrazilianHolidayImportUseCase>();
        services.AddScoped<ImportBrazilianHolidaysUseCase>();
        services.AddScoped<UpsertTimeEntryUseCase>();
        services.AddScoped<DeactivateTimeEntryUseCase>();
        services.AddScoped<AddTimeEntrySegmentUseCase>();
        services.AddScoped<UpdateTimeEntrySegmentUseCase>();
        services.AddScoped<DeactivateTimeEntrySegmentUseCase>();
        services.AddScoped<GetTimeEntryUseCase>();
        services.AddScoped<ListTimeEntriesUseCase>();
        services.AddScoped<OpenDailyCloseUseCase>();
        services.AddScoped<GetDailyCloseUseCase>();
        services.AddScoped<ListDailyClosesUseCase>();
        services.AddScoped<PutDailyCloseItemsUseCase>();
        services.AddScoped<SubmitDailyCloseUseCase>();
        services.AddScoped<ApproveDailyCloseUseCase>();
        services.AddScoped<RejectDailyCloseUseCase>();
        services.AddScoped<UserRegisterUseCase>();
        services.AddScoped<UserLoginUseCase>();
        services.AddScoped<UserRenewTokenUseCase>();
        services.AddScoped<PasswordEncryption>();
        services.AddScoped<IAuthenticationService, AuthenticationService>();
    }
}
