<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Validators.Test" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\server.Communication\server.Communication.csproj" />
      <ProjectReference Include="..\server.Domain\server.Domain.csproj" />
      <ProjectReference Include="..\server.Exceptions\server.Exceptions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    </ItemGroup>

</Project>
