using server.Application.Services.Transactions;
using server.Communication.Requests;
using server.Communication.Responses;
using server.Domain.Entities.Enums;
using server.Domain.Interfaces;
using server.Exceptions;
using server.Exceptions.Exceptions;

namespace server.Application.UseCases.Transactions.CreateInstallment;

public class CreateTransactionInstallmentUseCase(
    IAuthenticationService authenticationService,
    IOperatorsRepository operatorsRepository,
    ITransactionsRepository transactionsRepository,
    IUnitOfWork unitOfWork,
    TransactionBranchConsistencyService transactionBranchConsistencyService,
    LockDateGuard lockDateGuard,
    MemberAccountScopeGuard memberAccountScopeGuard)
{
    public async Task<ResponseCreateTransactionInstallmentJson> Execute(RequestCreateTransactionInstallmentJson request)
    {
        Validate(request);

        var branchUser = await authenticationService.GetAuthenticatedBranchUser();

        var callerOperator = await operatorsRepository
            .GetActiveLinkedByUserIdAndBranchIdAsNoTracking(branchUser.UserId, branchUser.BranchId);

        var recordedByOperatorId = TransactionBranchConsistencyService.RecordedByOperatorResolver(
            request.RecordedByOperatorId,
            branchUser.Role,
            callerOperator);

        var transactionType = await transactionBranchConsistencyService.ResolveAndValidate(
            branchId: branchUser.BranchId,
            accountId: request.AccountId,
            recordedByOperatorId: recordedByOperatorId,
            clientId: request.ClientId,
            transactionTypeId: request.TransactionTypeId);

        if (transactionType.SettlementRule != SettlementRule.OperatorEnteredCheque)
        {
            throw new ConflictException(ResourcesErrorMessages.TRANSACTION_INSTALLMENT_REQUIRES_CHEQUE);
        }

        await memberAccountScopeGuard.EnsureMemberCanActOnAccount(
            branchUser.Role,
            callerOperator?.Id,
            request.AccountId);

        await lockDateGuard.EnsureNotLocked(branchUser.BranchId, request.Date);

        var installmentPlan = BuildInstallmentPlan(request);
        var transactions = installmentPlan
            .Select(row => row.ToTransaction(
                request,
                transactionType,
                recordedByOperatorId,
                branchUser.UserId,
                branchUser.BranchId))
            .ToList();

        await transactionsRepository.AddRange(transactions);
        await unitOfWork.Commit();

        return transactions.ToCreateInstallmentResponse();
    }

    private static IReadOnlyList<CreateTransactionInstallmentRow> BuildInstallmentPlan(
        RequestCreateTransactionInstallmentJson request)
    {
        return request.AutoGenerateInstallments
            ? BuildAutoGeneratedInstallmentPlan(request)
            : BuildManualInstallmentPlan(request);
    }

    private static List<CreateTransactionInstallmentRow> BuildManualInstallmentPlan(RequestCreateTransactionInstallmentJson request)
    {
        var originId = Guid.NewGuid();
        var rows = request.Installments
            .Select((installment, index) => new CreateTransactionInstallmentRow(
                Id: index == 0 ? originId : Guid.NewGuid(),
                OriginTransactionId: originId,
                Value: installment.Value,
                DueDate: installment.DueDate,
                Description: BuildDescription(request.Description, index + 1, request.Installments.Count)))
            .ToList();

        EnsureAllInstallmentValuesPositive(rows);
        return rows;
    }

    private static List<CreateTransactionInstallmentRow> BuildAutoGeneratedInstallmentPlan(
        RequestCreateTransactionInstallmentJson request)
    {
        var n = request.InstallmentCount!.Value;
        var total = request.Value;
        var perInstallment = Math.Round(total / n, 2, MidpointRounding.AwayFromZero);
        var residualRow = total - perInstallment * (n - 1);
        var originId = Guid.NewGuid();
        var rows = new List<CreateTransactionInstallmentRow>(n);

        for (var i = 1; i <= n; i++)
        {
            var isLast = i == n;
            var rowValue = isLast ? residualRow : perInstallment;
            var rowDueDate = DueDateCalculator.AdjustToNextBusinessDay(request.DueDate!.Value.AddMonths(i - 1));

            rows.Add(new CreateTransactionInstallmentRow(
                Id: i == 1 ? originId : Guid.NewGuid(),
                OriginTransactionId: originId,
                Value: rowValue,
                DueDate: rowDueDate,
                Description: BuildDescription(request.Description, i, n)));
        }

        EnsureAllInstallmentValuesPositive(rows);
        return rows;
    }

    private static string BuildDescription(string? operatorDescription, int installmentNumber, int installmentCount)
    {
        var prefix = $"CH PRE ({installmentNumber}/{installmentCount})";

        return string.IsNullOrWhiteSpace(operatorDescription)
            ? prefix
            : $"{prefix} - {operatorDescription.Trim()}";
    }

    private static void EnsureAllInstallmentValuesPositive(IReadOnlyList<CreateTransactionInstallmentRow> rows)
    {
        if (rows.All(row => row.Value > 0m))
        {
            return;
        }

        throw new OnValidationException([ResourcesErrorMessages.TRANSACTION_INSTALLMENT_ROW_VALUE_MUST_BE_POSITIVE]);
    }

    private static void Validate(RequestCreateTransactionInstallmentJson request)
    {
        var result = new CreateTransactionInstallmentFluentValidation().Validate(request);
        if (result.IsValid is false)
        {
            throw new OnValidationException(result.Errors.Select(e => e.ErrorMessage).ToList());
        }
    }
}
